[theme]
# Primary accent color for interactive elements.
primaryColor = "#de8ba1"
# Background color for the main content area.
backgroundColor = "#f4f1ea"
# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#9fe4cc"
# Color used for almost all text.
textColor = "#262730"
